# Set base directory to "apps/fastrepl" in Netlify UI
[build]
command = "pnpm -F @hypr/fastrepl build"
publish = "apps/fastrepl/dist"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "/"
status = 200
