/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as XRouteImport } from './routes/x'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as JoinWaitlistRouteImport } from './routes/join-waitlist'
import { Route as GithubRouteImport } from './routes/github'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ViewRouteRouteImport } from './routes/_view/route'
import { Route as ViewIndexRouteImport } from './routes/_view/index'
import { Route as WebhookStripeRouteImport } from './routes/webhook/stripe'
import { Route as WebhookNangoRouteImport } from './routes/webhook/nango'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ViewTemplatesRouteImport } from './routes/_view/templates'
import { Route as ViewSecurityRouteImport } from './routes/_view/security'
import { Route as ViewRoadmapRouteImport } from './routes/_view/roadmap'
import { Route as ViewPricingRouteImport } from './routes/_view/pricing'
import { Route as ViewPressKitRouteImport } from './routes/_view/press-kit'
import { Route as ViewFileTranscriptionRouteImport } from './routes/_view/file-transcription'
import { Route as ViewFaqRouteImport } from './routes/_view/faq'
import { Route as ViewEnterpriseRouteImport } from './routes/_view/enterprise'
import { Route as ViewBrandRouteImport } from './routes/_view/brand'
import { Route as ViewAboutRouteImport } from './routes/_view/about'
import { Route as ViewVsRouteRouteImport } from './routes/_view/vs/route'
import { Route as ViewDocsRouteRouteImport } from './routes/_view/docs/route'
import { Route as ViewAppRouteRouteImport } from './routes/_view/app/route'
import { Route as ViewLegalIndexRouteImport } from './routes/_view/legal/index'
import { Route as ViewDownloadIndexRouteImport } from './routes/_view/download/index'
import { Route as ViewDocsIndexRouteImport } from './routes/_view/docs/index'
import { Route as ViewChangelogIndexRouteImport } from './routes/_view/changelog/index'
import { Route as ViewBlogIndexRouteImport } from './routes/_view/blog/index'
import { Route as ViewAppIndexRouteImport } from './routes/_view/app/index'
import { Route as ApiTweetIdRouteImport } from './routes/api/tweet.$id'
import { Route as ViewVsTldvRouteImport } from './routes/_view/vs/tldv'
import { Route as ViewVsTactiqRouteImport } from './routes/_view/vs/tactiq'
import { Route as ViewVsReflectRouteImport } from './routes/_view/vs/reflect'
import { Route as ViewVsReadAiRouteImport } from './routes/_view/vs/read-ai'
import { Route as ViewVsOtterRouteImport } from './routes/_view/vs/otter'
import { Route as ViewVsObsidianRouteImport } from './routes/_view/vs/obsidian'
import { Route as ViewVsNottaRouteImport } from './routes/_view/vs/notta'
import { Route as ViewVsNotionRouteImport } from './routes/_view/vs/notion'
import { Route as ViewVsNotabilityRouteImport } from './routes/_view/vs/notability'
import { Route as ViewVsMeetilyRouteImport } from './routes/_view/vs/meetily'
import { Route as ViewVsMeetgeekRouteImport } from './routes/_view/vs/meetgeek'
import { Route as ViewVsJamieRouteImport } from './routes/_view/vs/jamie'
import { Route as ViewVsGranolaRouteImport } from './routes/_view/vs/granola'
import { Route as ViewVsGongRouteImport } from './routes/_view/vs/gong'
import { Route as ViewVsFirefliesRouteImport } from './routes/_view/vs/fireflies'
import { Route as ViewVsFellowRouteImport } from './routes/_view/vs/fellow'
import { Route as ViewVsFathomRouteImport } from './routes/_view/vs/fathom'
import { Route as ViewVsEvernoteRouteImport } from './routes/_view/vs/evernote'
import { Route as ViewVsCluelyRouteImport } from './routes/_view/vs/cluely'
import { Route as ViewVsCirclebackRouteImport } from './routes/_view/vs/circleback'
import { Route as ViewVsBluedotRouteImport } from './routes/_view/vs/bluedot'
import { Route as ViewVsBearRouteImport } from './routes/_view/vs/bear'
import { Route as ViewVsAsideRouteImport } from './routes/_view/vs/aside'
import { Route as ViewSolutionSalesRouteImport } from './routes/_view/solution/sales'
import { Route as ViewSolutionRecruitingRouteImport } from './routes/_view/solution/recruiting'
import { Route as ViewSolutionProjectManagementRouteImport } from './routes/_view/solution/project-management'
import { Route as ViewSolutionMediaRouteImport } from './routes/_view/solution/media'
import { Route as ViewSolutionLegalRouteImport } from './routes/_view/solution/legal'
import { Route as ViewSolutionHealthcareRouteImport } from './routes/_view/solution/healthcare'
import { Route as ViewSolutionGovernmentRouteImport } from './routes/_view/solution/government'
import { Route as ViewSolutionFieldEngineeringRouteImport } from './routes/_view/solution/field-engineering'
import { Route as ViewSolutionCustomerSuccessRouteImport } from './routes/_view/solution/customer-success'
import { Route as ViewProductWorkflowsRouteImport } from './routes/_view/product/workflows'
import { Route as ViewProductSelfHostingRouteImport } from './routes/_view/product/self-hosting'
import { Route as ViewProductOpensourceRouteImport } from './routes/_view/product/opensource'
import { Route as ViewProductNotepadRouteImport } from './routes/_view/product/notepad'
import { Route as ViewProductMiniAppsRouteImport } from './routes/_view/product/mini-apps'
import { Route as ViewProductMemoryRouteImport } from './routes/_view/product/memory'
import { Route as ViewProductLocalAiRouteImport } from './routes/_view/product/local-ai'
import { Route as ViewProductExtensionsRouteImport } from './routes/_view/product/extensions'
import { Route as ViewProductBotRouteImport } from './routes/_view/product/bot'
import { Route as ViewProductApiRouteImport } from './routes/_view/product/api'
import { Route as ViewProductAiNotetakingRouteImport } from './routes/_view/product/ai-notetaking'
import { Route as ViewProductAiAssistantRouteImport } from './routes/_view/product/ai-assistant'
import { Route as ViewPressKitAppRouteImport } from './routes/_view/press-kit.app'
import { Route as ViewLegalSlugRouteImport } from './routes/_view/legal/$slug'
import { Route as ViewDownloadAppleSiliconRouteImport } from './routes/_view/download/apple-silicon'
import { Route as ViewDocsSplatRouteImport } from './routes/_view/docs/$'
import { Route as ViewChangelogSlugRouteImport } from './routes/_view/changelog/$slug'
import { Route as ViewCallbackAuthRouteImport } from './routes/_view/callback/auth'
import { Route as ViewBlogSlugRouteImport } from './routes/_view/blog/$slug'
import { Route as ViewAppIntegrationRouteImport } from './routes/_view/app/integration'
import { Route as ViewAppFileTranscriptionRouteImport } from './routes/_view/app/file-transcription'
import { Route as ViewAppCheckoutRouteImport } from './routes/_view/app/checkout'
import { Route as ViewAppAccountRouteImport } from './routes/_view/app/account'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinWaitlistRoute = JoinWaitlistRouteImport.update({
  id: '/join-waitlist',
  path: '/join-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRouteRoute = ViewRouteRouteImport.update({
  id: '/_view',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const WebhookStripeRoute = WebhookStripeRouteImport.update({
  id: '/webhook/stripe',
  path: '/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookNangoRoute = WebhookNangoRouteImport.update({
  id: '/webhook/nango',
  path: '/webhook/nango',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTemplatesRoute = ViewTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSecurityRoute = ViewSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewRoadmapRoute = ViewRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewPricingRoute = ViewPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewPressKitRoute = ViewPressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewFileTranscriptionRoute = ViewFileTranscriptionRouteImport.update({
  id: '/file-transcription',
  path: '/file-transcription',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewFaqRoute = ViewFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewEnterpriseRoute = ViewEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBrandRoute = ViewBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAboutRoute = ViewAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewVsRouteRoute = ViewVsRouteRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsRouteRoute = ViewDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppRouteRoute = ViewAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewLegalIndexRoute = ViewLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDownloadIndexRoute = ViewDownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsIndexRoute = ViewDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogIndexRoute = ViewChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogIndexRoute = ViewBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIndexRoute = ViewAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ApiTweetIdRoute = ApiTweetIdRouteImport.update({
  id: '/api/tweet/$id',
  path: '/api/tweet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewVsTldvRoute = ViewVsTldvRouteImport.update({
  id: '/tldv',
  path: '/tldv',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsTactiqRoute = ViewVsTactiqRouteImport.update({
  id: '/tactiq',
  path: '/tactiq',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsReflectRoute = ViewVsReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsReadAiRoute = ViewVsReadAiRouteImport.update({
  id: '/read-ai',
  path: '/read-ai',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsOtterRoute = ViewVsOtterRouteImport.update({
  id: '/otter',
  path: '/otter',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsObsidianRoute = ViewVsObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsNottaRoute = ViewVsNottaRouteImport.update({
  id: '/notta',
  path: '/notta',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsNotionRoute = ViewVsNotionRouteImport.update({
  id: '/notion',
  path: '/notion',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsNotabilityRoute = ViewVsNotabilityRouteImport.update({
  id: '/notability',
  path: '/notability',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsMeetilyRoute = ViewVsMeetilyRouteImport.update({
  id: '/meetily',
  path: '/meetily',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsMeetgeekRoute = ViewVsMeetgeekRouteImport.update({
  id: '/meetgeek',
  path: '/meetgeek',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsJamieRoute = ViewVsJamieRouteImport.update({
  id: '/jamie',
  path: '/jamie',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsGranolaRoute = ViewVsGranolaRouteImport.update({
  id: '/granola',
  path: '/granola',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsGongRoute = ViewVsGongRouteImport.update({
  id: '/gong',
  path: '/gong',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsFirefliesRoute = ViewVsFirefliesRouteImport.update({
  id: '/fireflies',
  path: '/fireflies',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsFellowRoute = ViewVsFellowRouteImport.update({
  id: '/fellow',
  path: '/fellow',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsFathomRoute = ViewVsFathomRouteImport.update({
  id: '/fathom',
  path: '/fathom',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsEvernoteRoute = ViewVsEvernoteRouteImport.update({
  id: '/evernote',
  path: '/evernote',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsCluelyRoute = ViewVsCluelyRouteImport.update({
  id: '/cluely',
  path: '/cluely',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsCirclebackRoute = ViewVsCirclebackRouteImport.update({
  id: '/circleback',
  path: '/circleback',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsBluedotRoute = ViewVsBluedotRouteImport.update({
  id: '/bluedot',
  path: '/bluedot',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsBearRoute = ViewVsBearRouteImport.update({
  id: '/bear',
  path: '/bear',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewVsAsideRoute = ViewVsAsideRouteImport.update({
  id: '/aside',
  path: '/aside',
  getParentRoute: () => ViewVsRouteRoute,
} as any)
const ViewSolutionSalesRoute = ViewSolutionSalesRouteImport.update({
  id: '/solution/sales',
  path: '/solution/sales',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionRecruitingRoute = ViewSolutionRecruitingRouteImport.update({
  id: '/solution/recruiting',
  path: '/solution/recruiting',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionProjectManagementRoute =
  ViewSolutionProjectManagementRouteImport.update({
    id: '/solution/project-management',
    path: '/solution/project-management',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewSolutionMediaRoute = ViewSolutionMediaRouteImport.update({
  id: '/solution/media',
  path: '/solution/media',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionLegalRoute = ViewSolutionLegalRouteImport.update({
  id: '/solution/legal',
  path: '/solution/legal',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionHealthcareRoute = ViewSolutionHealthcareRouteImport.update({
  id: '/solution/healthcare',
  path: '/solution/healthcare',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionGovernmentRoute = ViewSolutionGovernmentRouteImport.update({
  id: '/solution/government',
  path: '/solution/government',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewSolutionFieldEngineeringRoute =
  ViewSolutionFieldEngineeringRouteImport.update({
    id: '/solution/field-engineering',
    path: '/solution/field-engineering',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewSolutionCustomerSuccessRoute =
  ViewSolutionCustomerSuccessRouteImport.update({
    id: '/solution/customer-success',
    path: '/solution/customer-success',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewProductWorkflowsRoute = ViewProductWorkflowsRouteImport.update({
  id: '/product/workflows',
  path: '/product/workflows',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductSelfHostingRoute = ViewProductSelfHostingRouteImport.update({
  id: '/product/self-hosting',
  path: '/product/self-hosting',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductOpensourceRoute = ViewProductOpensourceRouteImport.update({
  id: '/product/opensource',
  path: '/product/opensource',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductNotepadRoute = ViewProductNotepadRouteImport.update({
  id: '/product/notepad',
  path: '/product/notepad',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductMiniAppsRoute = ViewProductMiniAppsRouteImport.update({
  id: '/product/mini-apps',
  path: '/product/mini-apps',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductMemoryRoute = ViewProductMemoryRouteImport.update({
  id: '/product/memory',
  path: '/product/memory',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductLocalAiRoute = ViewProductLocalAiRouteImport.update({
  id: '/product/local-ai',
  path: '/product/local-ai',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductExtensionsRoute = ViewProductExtensionsRouteImport.update({
  id: '/product/extensions',
  path: '/product/extensions',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductBotRoute = ViewProductBotRouteImport.update({
  id: '/product/bot',
  path: '/product/bot',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductApiRoute = ViewProductApiRouteImport.update({
  id: '/product/api',
  path: '/product/api',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductAiNotetakingRoute = ViewProductAiNotetakingRouteImport.update({
  id: '/product/ai-notetaking',
  path: '/product/ai-notetaking',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductAiAssistantRoute = ViewProductAiAssistantRouteImport.update({
  id: '/product/ai-assistant',
  path: '/product/ai-assistant',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewPressKitAppRoute = ViewPressKitAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ViewPressKitRoute,
} as any)
const ViewLegalSlugRoute = ViewLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDownloadAppleSiliconRoute =
  ViewDownloadAppleSiliconRouteImport.update({
    id: '/download/apple-silicon',
    path: '/download/apple-silicon',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewDocsSplatRoute = ViewDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogSlugRoute = ViewChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackAuthRoute = ViewCallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogSlugRoute = ViewBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIntegrationRoute = ViewAppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppFileTranscriptionRoute =
  ViewAppFileTranscriptionRouteImport.update({
    id: '/file-transcription',
    path: '/file-transcription',
    getParentRoute: () => ViewAppRouteRoute,
  } as any)
const ViewAppCheckoutRoute = ViewAppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppAccountRoute = ViewAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ViewAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/app': typeof ViewAppRouteRouteWithChildren
  '/docs': typeof ViewDocsRouteRouteWithChildren
  '/vs': typeof ViewVsRouteRouteWithChildren
  '/about': typeof ViewAboutRoute
  '/brand': typeof ViewBrandRoute
  '/enterprise': typeof ViewEnterpriseRoute
  '/faq': typeof ViewFaqRoute
  '/file-transcription': typeof ViewFileTranscriptionRoute
  '/press-kit': typeof ViewPressKitRouteWithChildren
  '/pricing': typeof ViewPricingRoute
  '/roadmap': typeof ViewRoadmapRoute
  '/security': typeof ViewSecurityRoute
  '/templates': typeof ViewTemplatesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/checkout': typeof ViewAppCheckoutRoute
  '/app/file-transcription': typeof ViewAppFileTranscriptionRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$': typeof ViewDocsSplatRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/press-kit/app': typeof ViewPressKitAppRoute
  '/product/ai-assistant': typeof ViewProductAiAssistantRoute
  '/product/ai-notetaking': typeof ViewProductAiNotetakingRoute
  '/product/api': typeof ViewProductApiRoute
  '/product/bot': typeof ViewProductBotRoute
  '/product/extensions': typeof ViewProductExtensionsRoute
  '/product/local-ai': typeof ViewProductLocalAiRoute
  '/product/memory': typeof ViewProductMemoryRoute
  '/product/mini-apps': typeof ViewProductMiniAppsRoute
  '/product/notepad': typeof ViewProductNotepadRoute
  '/product/opensource': typeof ViewProductOpensourceRoute
  '/product/self-hosting': typeof ViewProductSelfHostingRoute
  '/product/workflows': typeof ViewProductWorkflowsRoute
  '/solution/customer-success': typeof ViewSolutionCustomerSuccessRoute
  '/solution/field-engineering': typeof ViewSolutionFieldEngineeringRoute
  '/solution/government': typeof ViewSolutionGovernmentRoute
  '/solution/healthcare': typeof ViewSolutionHealthcareRoute
  '/solution/legal': typeof ViewSolutionLegalRoute
  '/solution/media': typeof ViewSolutionMediaRoute
  '/solution/project-management': typeof ViewSolutionProjectManagementRoute
  '/solution/recruiting': typeof ViewSolutionRecruitingRoute
  '/solution/sales': typeof ViewSolutionSalesRoute
  '/vs/aside': typeof ViewVsAsideRoute
  '/vs/bear': typeof ViewVsBearRoute
  '/vs/bluedot': typeof ViewVsBluedotRoute
  '/vs/circleback': typeof ViewVsCirclebackRoute
  '/vs/cluely': typeof ViewVsCluelyRoute
  '/vs/evernote': typeof ViewVsEvernoteRoute
  '/vs/fathom': typeof ViewVsFathomRoute
  '/vs/fellow': typeof ViewVsFellowRoute
  '/vs/fireflies': typeof ViewVsFirefliesRoute
  '/vs/gong': typeof ViewVsGongRoute
  '/vs/granola': typeof ViewVsGranolaRoute
  '/vs/jamie': typeof ViewVsJamieRoute
  '/vs/meetgeek': typeof ViewVsMeetgeekRoute
  '/vs/meetily': typeof ViewVsMeetilyRoute
  '/vs/notability': typeof ViewVsNotabilityRoute
  '/vs/notion': typeof ViewVsNotionRoute
  '/vs/notta': typeof ViewVsNottaRoute
  '/vs/obsidian': typeof ViewVsObsidianRoute
  '/vs/otter': typeof ViewVsOtterRoute
  '/vs/read-ai': typeof ViewVsReadAiRoute
  '/vs/reflect': typeof ViewVsReflectRoute
  '/vs/tactiq': typeof ViewVsTactiqRoute
  '/vs/tldv': typeof ViewVsTldvRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/app/': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs/': typeof ViewDocsIndexRoute
  '/download': typeof ViewDownloadIndexRoute
  '/legal': typeof ViewLegalIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/vs': typeof ViewVsRouteRouteWithChildren
  '/about': typeof ViewAboutRoute
  '/brand': typeof ViewBrandRoute
  '/enterprise': typeof ViewEnterpriseRoute
  '/faq': typeof ViewFaqRoute
  '/file-transcription': typeof ViewFileTranscriptionRoute
  '/press-kit': typeof ViewPressKitRouteWithChildren
  '/pricing': typeof ViewPricingRoute
  '/roadmap': typeof ViewRoadmapRoute
  '/security': typeof ViewSecurityRoute
  '/templates': typeof ViewTemplatesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/checkout': typeof ViewAppCheckoutRoute
  '/app/file-transcription': typeof ViewAppFileTranscriptionRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$': typeof ViewDocsSplatRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/press-kit/app': typeof ViewPressKitAppRoute
  '/product/ai-assistant': typeof ViewProductAiAssistantRoute
  '/product/ai-notetaking': typeof ViewProductAiNotetakingRoute
  '/product/api': typeof ViewProductApiRoute
  '/product/bot': typeof ViewProductBotRoute
  '/product/extensions': typeof ViewProductExtensionsRoute
  '/product/local-ai': typeof ViewProductLocalAiRoute
  '/product/memory': typeof ViewProductMemoryRoute
  '/product/mini-apps': typeof ViewProductMiniAppsRoute
  '/product/notepad': typeof ViewProductNotepadRoute
  '/product/opensource': typeof ViewProductOpensourceRoute
  '/product/self-hosting': typeof ViewProductSelfHostingRoute
  '/product/workflows': typeof ViewProductWorkflowsRoute
  '/solution/customer-success': typeof ViewSolutionCustomerSuccessRoute
  '/solution/field-engineering': typeof ViewSolutionFieldEngineeringRoute
  '/solution/government': typeof ViewSolutionGovernmentRoute
  '/solution/healthcare': typeof ViewSolutionHealthcareRoute
  '/solution/legal': typeof ViewSolutionLegalRoute
  '/solution/media': typeof ViewSolutionMediaRoute
  '/solution/project-management': typeof ViewSolutionProjectManagementRoute
  '/solution/recruiting': typeof ViewSolutionRecruitingRoute
  '/solution/sales': typeof ViewSolutionSalesRoute
  '/vs/aside': typeof ViewVsAsideRoute
  '/vs/bear': typeof ViewVsBearRoute
  '/vs/bluedot': typeof ViewVsBluedotRoute
  '/vs/circleback': typeof ViewVsCirclebackRoute
  '/vs/cluely': typeof ViewVsCluelyRoute
  '/vs/evernote': typeof ViewVsEvernoteRoute
  '/vs/fathom': typeof ViewVsFathomRoute
  '/vs/fellow': typeof ViewVsFellowRoute
  '/vs/fireflies': typeof ViewVsFirefliesRoute
  '/vs/gong': typeof ViewVsGongRoute
  '/vs/granola': typeof ViewVsGranolaRoute
  '/vs/jamie': typeof ViewVsJamieRoute
  '/vs/meetgeek': typeof ViewVsMeetgeekRoute
  '/vs/meetily': typeof ViewVsMeetilyRoute
  '/vs/notability': typeof ViewVsNotabilityRoute
  '/vs/notion': typeof ViewVsNotionRoute
  '/vs/notta': typeof ViewVsNottaRoute
  '/vs/obsidian': typeof ViewVsObsidianRoute
  '/vs/otter': typeof ViewVsOtterRoute
  '/vs/read-ai': typeof ViewVsReadAiRoute
  '/vs/reflect': typeof ViewVsReflectRoute
  '/vs/tactiq': typeof ViewVsTactiqRoute
  '/vs/tldv': typeof ViewVsTldvRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/app': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs': typeof ViewDocsIndexRoute
  '/download': typeof ViewDownloadIndexRoute
  '/legal': typeof ViewLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_view': typeof ViewRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/_view/app': typeof ViewAppRouteRouteWithChildren
  '/_view/docs': typeof ViewDocsRouteRouteWithChildren
  '/_view/vs': typeof ViewVsRouteRouteWithChildren
  '/_view/about': typeof ViewAboutRoute
  '/_view/brand': typeof ViewBrandRoute
  '/_view/enterprise': typeof ViewEnterpriseRoute
  '/_view/faq': typeof ViewFaqRoute
  '/_view/file-transcription': typeof ViewFileTranscriptionRoute
  '/_view/press-kit': typeof ViewPressKitRouteWithChildren
  '/_view/pricing': typeof ViewPricingRoute
  '/_view/roadmap': typeof ViewRoadmapRoute
  '/_view/security': typeof ViewSecurityRoute
  '/_view/templates': typeof ViewTemplatesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/_view/': typeof ViewIndexRoute
  '/_view/app/account': typeof ViewAppAccountRoute
  '/_view/app/checkout': typeof ViewAppCheckoutRoute
  '/_view/app/file-transcription': typeof ViewAppFileTranscriptionRoute
  '/_view/app/integration': typeof ViewAppIntegrationRoute
  '/_view/blog/$slug': typeof ViewBlogSlugRoute
  '/_view/callback/auth': typeof ViewCallbackAuthRoute
  '/_view/changelog/$slug': typeof ViewChangelogSlugRoute
  '/_view/docs/$': typeof ViewDocsSplatRoute
  '/_view/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/_view/legal/$slug': typeof ViewLegalSlugRoute
  '/_view/press-kit/app': typeof ViewPressKitAppRoute
  '/_view/product/ai-assistant': typeof ViewProductAiAssistantRoute
  '/_view/product/ai-notetaking': typeof ViewProductAiNotetakingRoute
  '/_view/product/api': typeof ViewProductApiRoute
  '/_view/product/bot': typeof ViewProductBotRoute
  '/_view/product/extensions': typeof ViewProductExtensionsRoute
  '/_view/product/local-ai': typeof ViewProductLocalAiRoute
  '/_view/product/memory': typeof ViewProductMemoryRoute
  '/_view/product/mini-apps': typeof ViewProductMiniAppsRoute
  '/_view/product/notepad': typeof ViewProductNotepadRoute
  '/_view/product/opensource': typeof ViewProductOpensourceRoute
  '/_view/product/self-hosting': typeof ViewProductSelfHostingRoute
  '/_view/product/workflows': typeof ViewProductWorkflowsRoute
  '/_view/solution/customer-success': typeof ViewSolutionCustomerSuccessRoute
  '/_view/solution/field-engineering': typeof ViewSolutionFieldEngineeringRoute
  '/_view/solution/government': typeof ViewSolutionGovernmentRoute
  '/_view/solution/healthcare': typeof ViewSolutionHealthcareRoute
  '/_view/solution/legal': typeof ViewSolutionLegalRoute
  '/_view/solution/media': typeof ViewSolutionMediaRoute
  '/_view/solution/project-management': typeof ViewSolutionProjectManagementRoute
  '/_view/solution/recruiting': typeof ViewSolutionRecruitingRoute
  '/_view/solution/sales': typeof ViewSolutionSalesRoute
  '/_view/vs/aside': typeof ViewVsAsideRoute
  '/_view/vs/bear': typeof ViewVsBearRoute
  '/_view/vs/bluedot': typeof ViewVsBluedotRoute
  '/_view/vs/circleback': typeof ViewVsCirclebackRoute
  '/_view/vs/cluely': typeof ViewVsCluelyRoute
  '/_view/vs/evernote': typeof ViewVsEvernoteRoute
  '/_view/vs/fathom': typeof ViewVsFathomRoute
  '/_view/vs/fellow': typeof ViewVsFellowRoute
  '/_view/vs/fireflies': typeof ViewVsFirefliesRoute
  '/_view/vs/gong': typeof ViewVsGongRoute
  '/_view/vs/granola': typeof ViewVsGranolaRoute
  '/_view/vs/jamie': typeof ViewVsJamieRoute
  '/_view/vs/meetgeek': typeof ViewVsMeetgeekRoute
  '/_view/vs/meetily': typeof ViewVsMeetilyRoute
  '/_view/vs/notability': typeof ViewVsNotabilityRoute
  '/_view/vs/notion': typeof ViewVsNotionRoute
  '/_view/vs/notta': typeof ViewVsNottaRoute
  '/_view/vs/obsidian': typeof ViewVsObsidianRoute
  '/_view/vs/otter': typeof ViewVsOtterRoute
  '/_view/vs/read-ai': typeof ViewVsReadAiRoute
  '/_view/vs/reflect': typeof ViewVsReflectRoute
  '/_view/vs/tactiq': typeof ViewVsTactiqRoute
  '/_view/vs/tldv': typeof ViewVsTldvRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/_view/app/': typeof ViewAppIndexRoute
  '/_view/blog/': typeof ViewBlogIndexRoute
  '/_view/changelog/': typeof ViewChangelogIndexRoute
  '/_view/docs/': typeof ViewDocsIndexRoute
  '/_view/download/': typeof ViewDownloadIndexRoute
  '/_view/legal/': typeof ViewLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/contact'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/youtube'
    | '/app'
    | '/docs'
    | '/vs'
    | '/about'
    | '/brand'
    | '/enterprise'
    | '/faq'
    | '/file-transcription'
    | '/press-kit'
    | '/pricing'
    | '/roadmap'
    | '/security'
    | '/templates'
    | '/api/templates'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/checkout'
    | '/app/file-transcription'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$'
    | '/download/apple-silicon'
    | '/legal/$slug'
    | '/press-kit/app'
    | '/product/ai-assistant'
    | '/product/ai-notetaking'
    | '/product/api'
    | '/product/bot'
    | '/product/extensions'
    | '/product/local-ai'
    | '/product/memory'
    | '/product/mini-apps'
    | '/product/notepad'
    | '/product/opensource'
    | '/product/self-hosting'
    | '/product/workflows'
    | '/solution/customer-success'
    | '/solution/field-engineering'
    | '/solution/government'
    | '/solution/healthcare'
    | '/solution/legal'
    | '/solution/media'
    | '/solution/project-management'
    | '/solution/recruiting'
    | '/solution/sales'
    | '/vs/aside'
    | '/vs/bear'
    | '/vs/bluedot'
    | '/vs/circleback'
    | '/vs/cluely'
    | '/vs/evernote'
    | '/vs/fathom'
    | '/vs/fellow'
    | '/vs/fireflies'
    | '/vs/gong'
    | '/vs/granola'
    | '/vs/jamie'
    | '/vs/meetgeek'
    | '/vs/meetily'
    | '/vs/notability'
    | '/vs/notion'
    | '/vs/notta'
    | '/vs/obsidian'
    | '/vs/otter'
    | '/vs/read-ai'
    | '/vs/reflect'
    | '/vs/tactiq'
    | '/vs/tldv'
    | '/api/tweet/$id'
    | '/app/'
    | '/blog'
    | '/changelog'
    | '/docs/'
    | '/download'
    | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contact'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/youtube'
    | '/vs'
    | '/about'
    | '/brand'
    | '/enterprise'
    | '/faq'
    | '/file-transcription'
    | '/press-kit'
    | '/pricing'
    | '/roadmap'
    | '/security'
    | '/templates'
    | '/api/templates'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/checkout'
    | '/app/file-transcription'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$'
    | '/download/apple-silicon'
    | '/legal/$slug'
    | '/press-kit/app'
    | '/product/ai-assistant'
    | '/product/ai-notetaking'
    | '/product/api'
    | '/product/bot'
    | '/product/extensions'
    | '/product/local-ai'
    | '/product/memory'
    | '/product/mini-apps'
    | '/product/notepad'
    | '/product/opensource'
    | '/product/self-hosting'
    | '/product/workflows'
    | '/solution/customer-success'
    | '/solution/field-engineering'
    | '/solution/government'
    | '/solution/healthcare'
    | '/solution/legal'
    | '/solution/media'
    | '/solution/project-management'
    | '/solution/recruiting'
    | '/solution/sales'
    | '/vs/aside'
    | '/vs/bear'
    | '/vs/bluedot'
    | '/vs/circleback'
    | '/vs/cluely'
    | '/vs/evernote'
    | '/vs/fathom'
    | '/vs/fellow'
    | '/vs/fireflies'
    | '/vs/gong'
    | '/vs/granola'
    | '/vs/jamie'
    | '/vs/meetgeek'
    | '/vs/meetily'
    | '/vs/notability'
    | '/vs/notion'
    | '/vs/notta'
    | '/vs/obsidian'
    | '/vs/otter'
    | '/vs/read-ai'
    | '/vs/reflect'
    | '/vs/tactiq'
    | '/vs/tldv'
    | '/api/tweet/$id'
    | '/app'
    | '/blog'
    | '/changelog'
    | '/docs'
    | '/download'
    | '/legal'
  id:
    | '__root__'
    | '/_view'
    | '/auth'
    | '/contact'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/youtube'
    | '/_view/app'
    | '/_view/docs'
    | '/_view/vs'
    | '/_view/about'
    | '/_view/brand'
    | '/_view/enterprise'
    | '/_view/faq'
    | '/_view/file-transcription'
    | '/_view/press-kit'
    | '/_view/pricing'
    | '/_view/roadmap'
    | '/_view/security'
    | '/_view/templates'
    | '/api/templates'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/_view/'
    | '/_view/app/account'
    | '/_view/app/checkout'
    | '/_view/app/file-transcription'
    | '/_view/app/integration'
    | '/_view/blog/$slug'
    | '/_view/callback/auth'
    | '/_view/changelog/$slug'
    | '/_view/docs/$'
    | '/_view/download/apple-silicon'
    | '/_view/legal/$slug'
    | '/_view/press-kit/app'
    | '/_view/product/ai-assistant'
    | '/_view/product/ai-notetaking'
    | '/_view/product/api'
    | '/_view/product/bot'
    | '/_view/product/extensions'
    | '/_view/product/local-ai'
    | '/_view/product/memory'
    | '/_view/product/mini-apps'
    | '/_view/product/notepad'
    | '/_view/product/opensource'
    | '/_view/product/self-hosting'
    | '/_view/product/workflows'
    | '/_view/solution/customer-success'
    | '/_view/solution/field-engineering'
    | '/_view/solution/government'
    | '/_view/solution/healthcare'
    | '/_view/solution/legal'
    | '/_view/solution/media'
    | '/_view/solution/project-management'
    | '/_view/solution/recruiting'
    | '/_view/solution/sales'
    | '/_view/vs/aside'
    | '/_view/vs/bear'
    | '/_view/vs/bluedot'
    | '/_view/vs/circleback'
    | '/_view/vs/cluely'
    | '/_view/vs/evernote'
    | '/_view/vs/fathom'
    | '/_view/vs/fellow'
    | '/_view/vs/fireflies'
    | '/_view/vs/gong'
    | '/_view/vs/granola'
    | '/_view/vs/jamie'
    | '/_view/vs/meetgeek'
    | '/_view/vs/meetily'
    | '/_view/vs/notability'
    | '/_view/vs/notion'
    | '/_view/vs/notta'
    | '/_view/vs/obsidian'
    | '/_view/vs/otter'
    | '/_view/vs/read-ai'
    | '/_view/vs/reflect'
    | '/_view/vs/tactiq'
    | '/_view/vs/tldv'
    | '/api/tweet/$id'
    | '/_view/app/'
    | '/_view/blog/'
    | '/_view/changelog/'
    | '/_view/docs/'
    | '/_view/download/'
    | '/_view/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ViewRouteRoute: typeof ViewRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DiscordRoute: typeof DiscordRoute
  FoundersRoute: typeof FoundersRoute
  GithubRoute: typeof GithubRoute
  JoinWaitlistRoute: typeof JoinWaitlistRoute
  LinkedinRoute: typeof LinkedinRoute
  XRoute: typeof XRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  WebhookNangoRoute: typeof WebhookNangoRoute
  WebhookStripeRoute: typeof WebhookStripeRoute
  ApiTweetIdRoute: typeof ApiTweetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-waitlist': {
      id: '/join-waitlist'
      path: '/join-waitlist'
      fullPath: '/join-waitlist'
      preLoaderRoute: typeof JoinWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view': {
      id: '/_view'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ViewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/': {
      id: '/_view/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/webhook/stripe': {
      id: '/webhook/stripe'
      path: '/webhook/stripe'
      fullPath: '/webhook/stripe'
      preLoaderRoute: typeof WebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/nango': {
      id: '/webhook/nango'
      path: '/webhook/nango'
      fullPath: '/webhook/nango'
      preLoaderRoute: typeof WebhookNangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/templates': {
      id: '/_view/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ViewTemplatesRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/security': {
      id: '/_view/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ViewSecurityRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/roadmap': {
      id: '/_view/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof ViewRoadmapRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/pricing': {
      id: '/_view/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ViewPricingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/press-kit': {
      id: '/_view/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof ViewPressKitRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/file-transcription': {
      id: '/_view/file-transcription'
      path: '/file-transcription'
      fullPath: '/file-transcription'
      preLoaderRoute: typeof ViewFileTranscriptionRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/faq': {
      id: '/_view/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof ViewFaqRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/enterprise': {
      id: '/_view/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof ViewEnterpriseRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/brand': {
      id: '/_view/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof ViewBrandRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/about': {
      id: '/_view/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ViewAboutRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/vs': {
      id: '/_view/vs'
      path: '/vs'
      fullPath: '/vs'
      preLoaderRoute: typeof ViewVsRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs': {
      id: '/_view/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ViewDocsRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app': {
      id: '/_view/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ViewAppRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/legal/': {
      id: '/_view/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof ViewLegalIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download/': {
      id: '/_view/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof ViewDownloadIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/': {
      id: '/_view/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof ViewDocsIndexRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/': {
      id: '/_view/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ViewChangelogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/': {
      id: '/_view/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof ViewBlogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/': {
      id: '/_view/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ViewAppIndexRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/api/tweet/$id': {
      id: '/api/tweet/$id'
      path: '/api/tweet/$id'
      fullPath: '/api/tweet/$id'
      preLoaderRoute: typeof ApiTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/vs/tldv': {
      id: '/_view/vs/tldv'
      path: '/tldv'
      fullPath: '/vs/tldv'
      preLoaderRoute: typeof ViewVsTldvRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/tactiq': {
      id: '/_view/vs/tactiq'
      path: '/tactiq'
      fullPath: '/vs/tactiq'
      preLoaderRoute: typeof ViewVsTactiqRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/reflect': {
      id: '/_view/vs/reflect'
      path: '/reflect'
      fullPath: '/vs/reflect'
      preLoaderRoute: typeof ViewVsReflectRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/read-ai': {
      id: '/_view/vs/read-ai'
      path: '/read-ai'
      fullPath: '/vs/read-ai'
      preLoaderRoute: typeof ViewVsReadAiRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/otter': {
      id: '/_view/vs/otter'
      path: '/otter'
      fullPath: '/vs/otter'
      preLoaderRoute: typeof ViewVsOtterRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/obsidian': {
      id: '/_view/vs/obsidian'
      path: '/obsidian'
      fullPath: '/vs/obsidian'
      preLoaderRoute: typeof ViewVsObsidianRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/notta': {
      id: '/_view/vs/notta'
      path: '/notta'
      fullPath: '/vs/notta'
      preLoaderRoute: typeof ViewVsNottaRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/notion': {
      id: '/_view/vs/notion'
      path: '/notion'
      fullPath: '/vs/notion'
      preLoaderRoute: typeof ViewVsNotionRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/notability': {
      id: '/_view/vs/notability'
      path: '/notability'
      fullPath: '/vs/notability'
      preLoaderRoute: typeof ViewVsNotabilityRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/meetily': {
      id: '/_view/vs/meetily'
      path: '/meetily'
      fullPath: '/vs/meetily'
      preLoaderRoute: typeof ViewVsMeetilyRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/meetgeek': {
      id: '/_view/vs/meetgeek'
      path: '/meetgeek'
      fullPath: '/vs/meetgeek'
      preLoaderRoute: typeof ViewVsMeetgeekRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/jamie': {
      id: '/_view/vs/jamie'
      path: '/jamie'
      fullPath: '/vs/jamie'
      preLoaderRoute: typeof ViewVsJamieRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/granola': {
      id: '/_view/vs/granola'
      path: '/granola'
      fullPath: '/vs/granola'
      preLoaderRoute: typeof ViewVsGranolaRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/gong': {
      id: '/_view/vs/gong'
      path: '/gong'
      fullPath: '/vs/gong'
      preLoaderRoute: typeof ViewVsGongRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/fireflies': {
      id: '/_view/vs/fireflies'
      path: '/fireflies'
      fullPath: '/vs/fireflies'
      preLoaderRoute: typeof ViewVsFirefliesRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/fellow': {
      id: '/_view/vs/fellow'
      path: '/fellow'
      fullPath: '/vs/fellow'
      preLoaderRoute: typeof ViewVsFellowRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/fathom': {
      id: '/_view/vs/fathom'
      path: '/fathom'
      fullPath: '/vs/fathom'
      preLoaderRoute: typeof ViewVsFathomRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/evernote': {
      id: '/_view/vs/evernote'
      path: '/evernote'
      fullPath: '/vs/evernote'
      preLoaderRoute: typeof ViewVsEvernoteRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/cluely': {
      id: '/_view/vs/cluely'
      path: '/cluely'
      fullPath: '/vs/cluely'
      preLoaderRoute: typeof ViewVsCluelyRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/circleback': {
      id: '/_view/vs/circleback'
      path: '/circleback'
      fullPath: '/vs/circleback'
      preLoaderRoute: typeof ViewVsCirclebackRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/bluedot': {
      id: '/_view/vs/bluedot'
      path: '/bluedot'
      fullPath: '/vs/bluedot'
      preLoaderRoute: typeof ViewVsBluedotRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/bear': {
      id: '/_view/vs/bear'
      path: '/bear'
      fullPath: '/vs/bear'
      preLoaderRoute: typeof ViewVsBearRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/vs/aside': {
      id: '/_view/vs/aside'
      path: '/aside'
      fullPath: '/vs/aside'
      preLoaderRoute: typeof ViewVsAsideRouteImport
      parentRoute: typeof ViewVsRouteRoute
    }
    '/_view/solution/sales': {
      id: '/_view/solution/sales'
      path: '/solution/sales'
      fullPath: '/solution/sales'
      preLoaderRoute: typeof ViewSolutionSalesRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/recruiting': {
      id: '/_view/solution/recruiting'
      path: '/solution/recruiting'
      fullPath: '/solution/recruiting'
      preLoaderRoute: typeof ViewSolutionRecruitingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/project-management': {
      id: '/_view/solution/project-management'
      path: '/solution/project-management'
      fullPath: '/solution/project-management'
      preLoaderRoute: typeof ViewSolutionProjectManagementRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/media': {
      id: '/_view/solution/media'
      path: '/solution/media'
      fullPath: '/solution/media'
      preLoaderRoute: typeof ViewSolutionMediaRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/legal': {
      id: '/_view/solution/legal'
      path: '/solution/legal'
      fullPath: '/solution/legal'
      preLoaderRoute: typeof ViewSolutionLegalRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/healthcare': {
      id: '/_view/solution/healthcare'
      path: '/solution/healthcare'
      fullPath: '/solution/healthcare'
      preLoaderRoute: typeof ViewSolutionHealthcareRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/government': {
      id: '/_view/solution/government'
      path: '/solution/government'
      fullPath: '/solution/government'
      preLoaderRoute: typeof ViewSolutionGovernmentRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/field-engineering': {
      id: '/_view/solution/field-engineering'
      path: '/solution/field-engineering'
      fullPath: '/solution/field-engineering'
      preLoaderRoute: typeof ViewSolutionFieldEngineeringRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/solution/customer-success': {
      id: '/_view/solution/customer-success'
      path: '/solution/customer-success'
      fullPath: '/solution/customer-success'
      preLoaderRoute: typeof ViewSolutionCustomerSuccessRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/workflows': {
      id: '/_view/product/workflows'
      path: '/product/workflows'
      fullPath: '/product/workflows'
      preLoaderRoute: typeof ViewProductWorkflowsRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/self-hosting': {
      id: '/_view/product/self-hosting'
      path: '/product/self-hosting'
      fullPath: '/product/self-hosting'
      preLoaderRoute: typeof ViewProductSelfHostingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/opensource': {
      id: '/_view/product/opensource'
      path: '/product/opensource'
      fullPath: '/product/opensource'
      preLoaderRoute: typeof ViewProductOpensourceRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/notepad': {
      id: '/_view/product/notepad'
      path: '/product/notepad'
      fullPath: '/product/notepad'
      preLoaderRoute: typeof ViewProductNotepadRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/mini-apps': {
      id: '/_view/product/mini-apps'
      path: '/product/mini-apps'
      fullPath: '/product/mini-apps'
      preLoaderRoute: typeof ViewProductMiniAppsRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/memory': {
      id: '/_view/product/memory'
      path: '/product/memory'
      fullPath: '/product/memory'
      preLoaderRoute: typeof ViewProductMemoryRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/local-ai': {
      id: '/_view/product/local-ai'
      path: '/product/local-ai'
      fullPath: '/product/local-ai'
      preLoaderRoute: typeof ViewProductLocalAiRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/extensions': {
      id: '/_view/product/extensions'
      path: '/product/extensions'
      fullPath: '/product/extensions'
      preLoaderRoute: typeof ViewProductExtensionsRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/bot': {
      id: '/_view/product/bot'
      path: '/product/bot'
      fullPath: '/product/bot'
      preLoaderRoute: typeof ViewProductBotRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/api': {
      id: '/_view/product/api'
      path: '/product/api'
      fullPath: '/product/api'
      preLoaderRoute: typeof ViewProductApiRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/ai-notetaking': {
      id: '/_view/product/ai-notetaking'
      path: '/product/ai-notetaking'
      fullPath: '/product/ai-notetaking'
      preLoaderRoute: typeof ViewProductAiNotetakingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/ai-assistant': {
      id: '/_view/product/ai-assistant'
      path: '/product/ai-assistant'
      fullPath: '/product/ai-assistant'
      preLoaderRoute: typeof ViewProductAiAssistantRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/press-kit/app': {
      id: '/_view/press-kit/app'
      path: '/app'
      fullPath: '/press-kit/app'
      preLoaderRoute: typeof ViewPressKitAppRouteImport
      parentRoute: typeof ViewPressKitRoute
    }
    '/_view/legal/$slug': {
      id: '/_view/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof ViewLegalSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download/apple-silicon': {
      id: '/_view/download/apple-silicon'
      path: '/download/apple-silicon'
      fullPath: '/download/apple-silicon'
      preLoaderRoute: typeof ViewDownloadAppleSiliconRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/$': {
      id: '/_view/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof ViewDocsSplatRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/$slug': {
      id: '/_view/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ViewChangelogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/auth': {
      id: '/_view/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof ViewCallbackAuthRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/$slug': {
      id: '/_view/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof ViewBlogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/integration': {
      id: '/_view/app/integration'
      path: '/integration'
      fullPath: '/app/integration'
      preLoaderRoute: typeof ViewAppIntegrationRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/file-transcription': {
      id: '/_view/app/file-transcription'
      path: '/file-transcription'
      fullPath: '/app/file-transcription'
      preLoaderRoute: typeof ViewAppFileTranscriptionRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/checkout': {
      id: '/_view/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof ViewAppCheckoutRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/account': {
      id: '/_view/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof ViewAppAccountRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
  }
}

interface ViewAppRouteRouteChildren {
  ViewAppAccountRoute: typeof ViewAppAccountRoute
  ViewAppCheckoutRoute: typeof ViewAppCheckoutRoute
  ViewAppFileTranscriptionRoute: typeof ViewAppFileTranscriptionRoute
  ViewAppIntegrationRoute: typeof ViewAppIntegrationRoute
  ViewAppIndexRoute: typeof ViewAppIndexRoute
}

const ViewAppRouteRouteChildren: ViewAppRouteRouteChildren = {
  ViewAppAccountRoute: ViewAppAccountRoute,
  ViewAppCheckoutRoute: ViewAppCheckoutRoute,
  ViewAppFileTranscriptionRoute: ViewAppFileTranscriptionRoute,
  ViewAppIntegrationRoute: ViewAppIntegrationRoute,
  ViewAppIndexRoute: ViewAppIndexRoute,
}

const ViewAppRouteRouteWithChildren = ViewAppRouteRoute._addFileChildren(
  ViewAppRouteRouteChildren,
)

interface ViewDocsRouteRouteChildren {
  ViewDocsSplatRoute: typeof ViewDocsSplatRoute
  ViewDocsIndexRoute: typeof ViewDocsIndexRoute
}

const ViewDocsRouteRouteChildren: ViewDocsRouteRouteChildren = {
  ViewDocsSplatRoute: ViewDocsSplatRoute,
  ViewDocsIndexRoute: ViewDocsIndexRoute,
}

const ViewDocsRouteRouteWithChildren = ViewDocsRouteRoute._addFileChildren(
  ViewDocsRouteRouteChildren,
)

interface ViewVsRouteRouteChildren {
  ViewVsAsideRoute: typeof ViewVsAsideRoute
  ViewVsBearRoute: typeof ViewVsBearRoute
  ViewVsBluedotRoute: typeof ViewVsBluedotRoute
  ViewVsCirclebackRoute: typeof ViewVsCirclebackRoute
  ViewVsCluelyRoute: typeof ViewVsCluelyRoute
  ViewVsEvernoteRoute: typeof ViewVsEvernoteRoute
  ViewVsFathomRoute: typeof ViewVsFathomRoute
  ViewVsFellowRoute: typeof ViewVsFellowRoute
  ViewVsFirefliesRoute: typeof ViewVsFirefliesRoute
  ViewVsGongRoute: typeof ViewVsGongRoute
  ViewVsGranolaRoute: typeof ViewVsGranolaRoute
  ViewVsJamieRoute: typeof ViewVsJamieRoute
  ViewVsMeetgeekRoute: typeof ViewVsMeetgeekRoute
  ViewVsMeetilyRoute: typeof ViewVsMeetilyRoute
  ViewVsNotabilityRoute: typeof ViewVsNotabilityRoute
  ViewVsNotionRoute: typeof ViewVsNotionRoute
  ViewVsNottaRoute: typeof ViewVsNottaRoute
  ViewVsObsidianRoute: typeof ViewVsObsidianRoute
  ViewVsOtterRoute: typeof ViewVsOtterRoute
  ViewVsReadAiRoute: typeof ViewVsReadAiRoute
  ViewVsReflectRoute: typeof ViewVsReflectRoute
  ViewVsTactiqRoute: typeof ViewVsTactiqRoute
  ViewVsTldvRoute: typeof ViewVsTldvRoute
}

const ViewVsRouteRouteChildren: ViewVsRouteRouteChildren = {
  ViewVsAsideRoute: ViewVsAsideRoute,
  ViewVsBearRoute: ViewVsBearRoute,
  ViewVsBluedotRoute: ViewVsBluedotRoute,
  ViewVsCirclebackRoute: ViewVsCirclebackRoute,
  ViewVsCluelyRoute: ViewVsCluelyRoute,
  ViewVsEvernoteRoute: ViewVsEvernoteRoute,
  ViewVsFathomRoute: ViewVsFathomRoute,
  ViewVsFellowRoute: ViewVsFellowRoute,
  ViewVsFirefliesRoute: ViewVsFirefliesRoute,
  ViewVsGongRoute: ViewVsGongRoute,
  ViewVsGranolaRoute: ViewVsGranolaRoute,
  ViewVsJamieRoute: ViewVsJamieRoute,
  ViewVsMeetgeekRoute: ViewVsMeetgeekRoute,
  ViewVsMeetilyRoute: ViewVsMeetilyRoute,
  ViewVsNotabilityRoute: ViewVsNotabilityRoute,
  ViewVsNotionRoute: ViewVsNotionRoute,
  ViewVsNottaRoute: ViewVsNottaRoute,
  ViewVsObsidianRoute: ViewVsObsidianRoute,
  ViewVsOtterRoute: ViewVsOtterRoute,
  ViewVsReadAiRoute: ViewVsReadAiRoute,
  ViewVsReflectRoute: ViewVsReflectRoute,
  ViewVsTactiqRoute: ViewVsTactiqRoute,
  ViewVsTldvRoute: ViewVsTldvRoute,
}

const ViewVsRouteRouteWithChildren = ViewVsRouteRoute._addFileChildren(
  ViewVsRouteRouteChildren,
)

interface ViewPressKitRouteChildren {
  ViewPressKitAppRoute: typeof ViewPressKitAppRoute
}

const ViewPressKitRouteChildren: ViewPressKitRouteChildren = {
  ViewPressKitAppRoute: ViewPressKitAppRoute,
}

const ViewPressKitRouteWithChildren = ViewPressKitRoute._addFileChildren(
  ViewPressKitRouteChildren,
)

interface ViewRouteRouteChildren {
  ViewAppRouteRoute: typeof ViewAppRouteRouteWithChildren
  ViewDocsRouteRoute: typeof ViewDocsRouteRouteWithChildren
  ViewVsRouteRoute: typeof ViewVsRouteRouteWithChildren
  ViewAboutRoute: typeof ViewAboutRoute
  ViewBrandRoute: typeof ViewBrandRoute
  ViewEnterpriseRoute: typeof ViewEnterpriseRoute
  ViewFaqRoute: typeof ViewFaqRoute
  ViewFileTranscriptionRoute: typeof ViewFileTranscriptionRoute
  ViewPressKitRoute: typeof ViewPressKitRouteWithChildren
  ViewPricingRoute: typeof ViewPricingRoute
  ViewRoadmapRoute: typeof ViewRoadmapRoute
  ViewSecurityRoute: typeof ViewSecurityRoute
  ViewTemplatesRoute: typeof ViewTemplatesRoute
  ViewIndexRoute: typeof ViewIndexRoute
  ViewBlogSlugRoute: typeof ViewBlogSlugRoute
  ViewCallbackAuthRoute: typeof ViewCallbackAuthRoute
  ViewChangelogSlugRoute: typeof ViewChangelogSlugRoute
  ViewDownloadAppleSiliconRoute: typeof ViewDownloadAppleSiliconRoute
  ViewLegalSlugRoute: typeof ViewLegalSlugRoute
  ViewProductAiAssistantRoute: typeof ViewProductAiAssistantRoute
  ViewProductAiNotetakingRoute: typeof ViewProductAiNotetakingRoute
  ViewProductApiRoute: typeof ViewProductApiRoute
  ViewProductBotRoute: typeof ViewProductBotRoute
  ViewProductExtensionsRoute: typeof ViewProductExtensionsRoute
  ViewProductLocalAiRoute: typeof ViewProductLocalAiRoute
  ViewProductMemoryRoute: typeof ViewProductMemoryRoute
  ViewProductMiniAppsRoute: typeof ViewProductMiniAppsRoute
  ViewProductNotepadRoute: typeof ViewProductNotepadRoute
  ViewProductOpensourceRoute: typeof ViewProductOpensourceRoute
  ViewProductSelfHostingRoute: typeof ViewProductSelfHostingRoute
  ViewProductWorkflowsRoute: typeof ViewProductWorkflowsRoute
  ViewSolutionCustomerSuccessRoute: typeof ViewSolutionCustomerSuccessRoute
  ViewSolutionFieldEngineeringRoute: typeof ViewSolutionFieldEngineeringRoute
  ViewSolutionGovernmentRoute: typeof ViewSolutionGovernmentRoute
  ViewSolutionHealthcareRoute: typeof ViewSolutionHealthcareRoute
  ViewSolutionLegalRoute: typeof ViewSolutionLegalRoute
  ViewSolutionMediaRoute: typeof ViewSolutionMediaRoute
  ViewSolutionProjectManagementRoute: typeof ViewSolutionProjectManagementRoute
  ViewSolutionRecruitingRoute: typeof ViewSolutionRecruitingRoute
  ViewSolutionSalesRoute: typeof ViewSolutionSalesRoute
  ViewBlogIndexRoute: typeof ViewBlogIndexRoute
  ViewChangelogIndexRoute: typeof ViewChangelogIndexRoute
  ViewDownloadIndexRoute: typeof ViewDownloadIndexRoute
  ViewLegalIndexRoute: typeof ViewLegalIndexRoute
}

const ViewRouteRouteChildren: ViewRouteRouteChildren = {
  ViewAppRouteRoute: ViewAppRouteRouteWithChildren,
  ViewDocsRouteRoute: ViewDocsRouteRouteWithChildren,
  ViewVsRouteRoute: ViewVsRouteRouteWithChildren,
  ViewAboutRoute: ViewAboutRoute,
  ViewBrandRoute: ViewBrandRoute,
  ViewEnterpriseRoute: ViewEnterpriseRoute,
  ViewFaqRoute: ViewFaqRoute,
  ViewFileTranscriptionRoute: ViewFileTranscriptionRoute,
  ViewPressKitRoute: ViewPressKitRouteWithChildren,
  ViewPricingRoute: ViewPricingRoute,
  ViewRoadmapRoute: ViewRoadmapRoute,
  ViewSecurityRoute: ViewSecurityRoute,
  ViewTemplatesRoute: ViewTemplatesRoute,
  ViewIndexRoute: ViewIndexRoute,
  ViewBlogSlugRoute: ViewBlogSlugRoute,
  ViewCallbackAuthRoute: ViewCallbackAuthRoute,
  ViewChangelogSlugRoute: ViewChangelogSlugRoute,
  ViewDownloadAppleSiliconRoute: ViewDownloadAppleSiliconRoute,
  ViewLegalSlugRoute: ViewLegalSlugRoute,
  ViewProductAiAssistantRoute: ViewProductAiAssistantRoute,
  ViewProductAiNotetakingRoute: ViewProductAiNotetakingRoute,
  ViewProductApiRoute: ViewProductApiRoute,
  ViewProductBotRoute: ViewProductBotRoute,
  ViewProductExtensionsRoute: ViewProductExtensionsRoute,
  ViewProductLocalAiRoute: ViewProductLocalAiRoute,
  ViewProductMemoryRoute: ViewProductMemoryRoute,
  ViewProductMiniAppsRoute: ViewProductMiniAppsRoute,
  ViewProductNotepadRoute: ViewProductNotepadRoute,
  ViewProductOpensourceRoute: ViewProductOpensourceRoute,
  ViewProductSelfHostingRoute: ViewProductSelfHostingRoute,
  ViewProductWorkflowsRoute: ViewProductWorkflowsRoute,
  ViewSolutionCustomerSuccessRoute: ViewSolutionCustomerSuccessRoute,
  ViewSolutionFieldEngineeringRoute: ViewSolutionFieldEngineeringRoute,
  ViewSolutionGovernmentRoute: ViewSolutionGovernmentRoute,
  ViewSolutionHealthcareRoute: ViewSolutionHealthcareRoute,
  ViewSolutionLegalRoute: ViewSolutionLegalRoute,
  ViewSolutionMediaRoute: ViewSolutionMediaRoute,
  ViewSolutionProjectManagementRoute: ViewSolutionProjectManagementRoute,
  ViewSolutionRecruitingRoute: ViewSolutionRecruitingRoute,
  ViewSolutionSalesRoute: ViewSolutionSalesRoute,
  ViewBlogIndexRoute: ViewBlogIndexRoute,
  ViewChangelogIndexRoute: ViewChangelogIndexRoute,
  ViewDownloadIndexRoute: ViewDownloadIndexRoute,
  ViewLegalIndexRoute: ViewLegalIndexRoute,
}

const ViewRouteRouteWithChildren = ViewRouteRoute._addFileChildren(
  ViewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ViewRouteRoute: ViewRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DiscordRoute: DiscordRoute,
  FoundersRoute: FoundersRoute,
  GithubRoute: GithubRoute,
  JoinWaitlistRoute: JoinWaitlistRoute,
  LinkedinRoute: LinkedinRoute,
  XRoute: XRoute,
  YoutubeRoute: YoutubeRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  WebhookNangoRoute: WebhookNangoRoute,
  WebhookStripeRoute: WebhookStripeRoute,
  ApiTweetIdRoute: ApiTweetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
