/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalRouteImport } from './routes/cal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ViewRouteRouteImport } from './routes/_view/route'
import { Route as ViewIndexRouteImport } from './routes/_view/index'
import { Route as WebhookStripeRouteImport } from './routes/webhook/stripe'
import { Route as WebhookNangoRouteImport } from './routes/webhook/nango'
import { Route as ViewPricingRouteImport } from './routes/_view/pricing'
import { Route as ViewDownloadRouteImport } from './routes/_view/download'
import { Route as ViewDocsRouteRouteImport } from './routes/_view/docs/route'
import { Route as ViewAppRouteRouteImport } from './routes/_view/app/route'
import { Route as ViewProductIndexRouteImport } from './routes/_view/product/index'
import { Route as ViewLegalIndexRouteImport } from './routes/_view/legal/index'
import { Route as ViewDocsIndexRouteImport } from './routes/_view/docs/index'
import { Route as ViewChangelogIndexRouteImport } from './routes/_view/changelog/index'
import { Route as ViewBlogIndexRouteImport } from './routes/_view/blog/index'
import { Route as ViewAppIndexRouteImport } from './routes/_view/app/index'
import { Route as ApiSyncWriteRouteImport } from './routes/api/sync.write'
import { Route as ApiSyncReadRouteImport } from './routes/api/sync.read'
import { Route as ViewLegalSlugRouteImport } from './routes/_view/legal/$slug'
import { Route as ViewDocsSlugRouteImport } from './routes/_view/docs/$slug'
import { Route as ViewChangelogSlugRouteImport } from './routes/_view/changelog/$slug'
import { Route as ViewCallbackAuthRouteImport } from './routes/_view/callback/auth'
import { Route as ViewBlogSlugRouteImport } from './routes/_view/blog/$slug'
import { Route as ViewAppIntegrationRouteImport } from './routes/_view/app/integration'
import { Route as ViewAppAccountRouteImport } from './routes/_view/app/account'

const CalRoute = CalRouteImport.update({
  id: '/cal',
  path: '/cal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRouteRoute = ViewRouteRouteImport.update({
  id: '/_view',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const WebhookStripeRoute = WebhookStripeRouteImport.update({
  id: '/webhook/stripe',
  path: '/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookNangoRoute = WebhookNangoRouteImport.update({
  id: '/webhook/nango',
  path: '/webhook/nango',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewPricingRoute = ViewPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDownloadRoute = ViewDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsRouteRoute = ViewDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppRouteRoute = ViewAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductIndexRoute = ViewProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewLegalIndexRoute = ViewLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsIndexRoute = ViewDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogIndexRoute = ViewChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogIndexRoute = ViewBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIndexRoute = ViewAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ApiSyncWriteRoute = ApiSyncWriteRouteImport.update({
  id: '/api/sync/write',
  path: '/api/sync/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncReadRoute = ApiSyncReadRouteImport.update({
  id: '/api/sync/read',
  path: '/api/sync/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewLegalSlugRoute = ViewLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsSlugRoute = ViewDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogSlugRoute = ViewChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackAuthRoute = ViewCallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogSlugRoute = ViewBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIntegrationRoute = ViewAppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppAccountRoute = ViewAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ViewAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/app': typeof ViewAppRouteRouteWithChildren
  '/docs': typeof ViewDocsRouteRouteWithChildren
  '/download': typeof ViewDownloadRoute
  '/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$slug': typeof ViewDocsSlugRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/api/sync/read': typeof ApiSyncReadRoute
  '/api/sync/write': typeof ApiSyncWriteRoute
  '/app/': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs/': typeof ViewDocsIndexRoute
  '/legal': typeof ViewLegalIndexRoute
  '/product': typeof ViewProductIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/download': typeof ViewDownloadRoute
  '/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$slug': typeof ViewDocsSlugRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/api/sync/read': typeof ApiSyncReadRoute
  '/api/sync/write': typeof ApiSyncWriteRoute
  '/app': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs': typeof ViewDocsIndexRoute
  '/legal': typeof ViewLegalIndexRoute
  '/product': typeof ViewProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_view': typeof ViewRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/_view/app': typeof ViewAppRouteRouteWithChildren
  '/_view/docs': typeof ViewDocsRouteRouteWithChildren
  '/_view/download': typeof ViewDownloadRoute
  '/_view/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/_view/': typeof ViewIndexRoute
  '/_view/app/account': typeof ViewAppAccountRoute
  '/_view/app/integration': typeof ViewAppIntegrationRoute
  '/_view/blog/$slug': typeof ViewBlogSlugRoute
  '/_view/callback/auth': typeof ViewCallbackAuthRoute
  '/_view/changelog/$slug': typeof ViewChangelogSlugRoute
  '/_view/docs/$slug': typeof ViewDocsSlugRoute
  '/_view/legal/$slug': typeof ViewLegalSlugRoute
  '/api/sync/read': typeof ApiSyncReadRoute
  '/api/sync/write': typeof ApiSyncWriteRoute
  '/_view/app/': typeof ViewAppIndexRoute
  '/_view/blog/': typeof ViewBlogIndexRoute
  '/_view/changelog/': typeof ViewChangelogIndexRoute
  '/_view/docs/': typeof ViewDocsIndexRoute
  '/_view/legal/': typeof ViewLegalIndexRoute
  '/_view/product/': typeof ViewProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/cal'
    | '/app'
    | '/docs'
    | '/download'
    | '/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$slug'
    | '/legal/$slug'
    | '/api/sync/read'
    | '/api/sync/write'
    | '/app/'
    | '/blog'
    | '/changelog'
    | '/docs/'
    | '/legal'
    | '/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cal'
    | '/download'
    | '/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$slug'
    | '/legal/$slug'
    | '/api/sync/read'
    | '/api/sync/write'
    | '/app'
    | '/blog'
    | '/changelog'
    | '/docs'
    | '/legal'
    | '/product'
  id:
    | '__root__'
    | '/_view'
    | '/auth'
    | '/cal'
    | '/_view/app'
    | '/_view/docs'
    | '/_view/download'
    | '/_view/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/_view/'
    | '/_view/app/account'
    | '/_view/app/integration'
    | '/_view/blog/$slug'
    | '/_view/callback/auth'
    | '/_view/changelog/$slug'
    | '/_view/docs/$slug'
    | '/_view/legal/$slug'
    | '/api/sync/read'
    | '/api/sync/write'
    | '/_view/app/'
    | '/_view/blog/'
    | '/_view/changelog/'
    | '/_view/docs/'
    | '/_view/legal/'
    | '/_view/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ViewRouteRoute: typeof ViewRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalRoute: typeof CalRoute
  WebhookNangoRoute: typeof WebhookNangoRoute
  WebhookStripeRoute: typeof WebhookStripeRoute
  ApiSyncReadRoute: typeof ApiSyncReadRoute
  ApiSyncWriteRoute: typeof ApiSyncWriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cal': {
      id: '/cal'
      path: '/cal'
      fullPath: '/cal'
      preLoaderRoute: typeof CalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view': {
      id: '/_view'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ViewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/': {
      id: '/_view/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/webhook/stripe': {
      id: '/webhook/stripe'
      path: '/webhook/stripe'
      fullPath: '/webhook/stripe'
      preLoaderRoute: typeof WebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/nango': {
      id: '/webhook/nango'
      path: '/webhook/nango'
      fullPath: '/webhook/nango'
      preLoaderRoute: typeof WebhookNangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/pricing': {
      id: '/_view/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ViewPricingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download': {
      id: '/_view/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof ViewDownloadRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs': {
      id: '/_view/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ViewDocsRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app': {
      id: '/_view/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ViewAppRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/': {
      id: '/_view/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ViewProductIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/legal/': {
      id: '/_view/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof ViewLegalIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/': {
      id: '/_view/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof ViewDocsIndexRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/': {
      id: '/_view/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ViewChangelogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/': {
      id: '/_view/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof ViewBlogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/': {
      id: '/_view/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ViewAppIndexRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/api/sync/write': {
      id: '/api/sync/write'
      path: '/api/sync/write'
      fullPath: '/api/sync/write'
      preLoaderRoute: typeof ApiSyncWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/read': {
      id: '/api/sync/read'
      path: '/api/sync/read'
      fullPath: '/api/sync/read'
      preLoaderRoute: typeof ApiSyncReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/legal/$slug': {
      id: '/_view/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof ViewLegalSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/$slug': {
      id: '/_view/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof ViewDocsSlugRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/$slug': {
      id: '/_view/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ViewChangelogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/auth': {
      id: '/_view/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof ViewCallbackAuthRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/$slug': {
      id: '/_view/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof ViewBlogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/integration': {
      id: '/_view/app/integration'
      path: '/integration'
      fullPath: '/app/integration'
      preLoaderRoute: typeof ViewAppIntegrationRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/account': {
      id: '/_view/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof ViewAppAccountRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
  }
}

interface ViewAppRouteRouteChildren {
  ViewAppAccountRoute: typeof ViewAppAccountRoute
  ViewAppIntegrationRoute: typeof ViewAppIntegrationRoute
  ViewAppIndexRoute: typeof ViewAppIndexRoute
}

const ViewAppRouteRouteChildren: ViewAppRouteRouteChildren = {
  ViewAppAccountRoute: ViewAppAccountRoute,
  ViewAppIntegrationRoute: ViewAppIntegrationRoute,
  ViewAppIndexRoute: ViewAppIndexRoute,
}

const ViewAppRouteRouteWithChildren = ViewAppRouteRoute._addFileChildren(
  ViewAppRouteRouteChildren,
)

interface ViewDocsRouteRouteChildren {
  ViewDocsSlugRoute: typeof ViewDocsSlugRoute
  ViewDocsIndexRoute: typeof ViewDocsIndexRoute
}

const ViewDocsRouteRouteChildren: ViewDocsRouteRouteChildren = {
  ViewDocsSlugRoute: ViewDocsSlugRoute,
  ViewDocsIndexRoute: ViewDocsIndexRoute,
}

const ViewDocsRouteRouteWithChildren = ViewDocsRouteRoute._addFileChildren(
  ViewDocsRouteRouteChildren,
)

interface ViewRouteRouteChildren {
  ViewAppRouteRoute: typeof ViewAppRouteRouteWithChildren
  ViewDocsRouteRoute: typeof ViewDocsRouteRouteWithChildren
  ViewDownloadRoute: typeof ViewDownloadRoute
  ViewPricingRoute: typeof ViewPricingRoute
  ViewIndexRoute: typeof ViewIndexRoute
  ViewBlogSlugRoute: typeof ViewBlogSlugRoute
  ViewCallbackAuthRoute: typeof ViewCallbackAuthRoute
  ViewChangelogSlugRoute: typeof ViewChangelogSlugRoute
  ViewLegalSlugRoute: typeof ViewLegalSlugRoute
  ViewBlogIndexRoute: typeof ViewBlogIndexRoute
  ViewChangelogIndexRoute: typeof ViewChangelogIndexRoute
  ViewLegalIndexRoute: typeof ViewLegalIndexRoute
  ViewProductIndexRoute: typeof ViewProductIndexRoute
}

const ViewRouteRouteChildren: ViewRouteRouteChildren = {
  ViewAppRouteRoute: ViewAppRouteRouteWithChildren,
  ViewDocsRouteRoute: ViewDocsRouteRouteWithChildren,
  ViewDownloadRoute: ViewDownloadRoute,
  ViewPricingRoute: ViewPricingRoute,
  ViewIndexRoute: ViewIndexRoute,
  ViewBlogSlugRoute: ViewBlogSlugRoute,
  ViewCallbackAuthRoute: ViewCallbackAuthRoute,
  ViewChangelogSlugRoute: ViewChangelogSlugRoute,
  ViewLegalSlugRoute: ViewLegalSlugRoute,
  ViewBlogIndexRoute: ViewBlogIndexRoute,
  ViewChangelogIndexRoute: ViewChangelogIndexRoute,
  ViewLegalIndexRoute: ViewLegalIndexRoute,
  ViewProductIndexRoute: ViewProductIndexRoute,
}

const ViewRouteRouteWithChildren = ViewRouteRoute._addFileChildren(
  ViewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ViewRouteRoute: ViewRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalRoute: CalRoute,
  WebhookNangoRoute: WebhookNangoRoute,
  WebhookStripeRoute: WebhookStripeRoute,
  ApiSyncReadRoute: ApiSyncReadRoute,
  ApiSyncWriteRoute: ApiSyncWriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
