// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openCalendar() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|open_calendar") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openCalendarAccessSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|open_calendar_access_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openContactsAccessSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|open_contacts_access_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calendarAccessStatus() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:apple-calendar|calendar_access_status");
},
async contactsAccessStatus() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:apple-calendar|contacts_access_status");
},
async hasCalendarAccess() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:apple-calendar|has_calendar_access");
},
async hasContactsAccess() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:apple-calendar|has_contacts_access");
},
async requestCalendarAccess() : Promise<void> {
    await TAURI_INVOKE("plugin:apple-calendar|request_calendar_access");
},
async requestContactsAccess() : Promise<void> {
    await TAURI_INVOKE("plugin:apple-calendar|request_contacts_access");
},
async revokeCalendarAccess() : Promise<void> {
    await TAURI_INVOKE("plugin:apple-calendar|revoke_calendar_access");
},
async revokeContactsAccess() : Promise<void> {
    await TAURI_INVOKE("plugin:apple-calendar|revoke_contacts_access");
},
async listCalendars() : Promise<Result<Calendar[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(filter: EventFilter) : Promise<Result<Event[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|list_events", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Calendar = { id: string; platform: Platform; name: string; source: string | null }
export type Event = { id: string; calendar_id: string; platform: Platform; name: string; note: string; participants: Participant[]; start_date: string; end_date: string; google_event_url: string | null; recurrence: RecurrenceInfo | null }
export type EventFilter = { from: string; to: string; calendar_tracking_id: string }
export type Participant = { name: string; email: string | null }
export type Platform = "Apple"
export type RecurrenceEnd = { Date: string } | { Count: number }
export type RecurrenceFrequency = "Daily" | "Weekly" | "Monthly" | "Yearly"
export type RecurrenceInfo = { series_id: string; occurrence_date: string; is_detached: boolean; rule: RecurrenceRule | null }
export type RecurrenceRule = { frequency: RecurrenceFrequency; interval: number; end: RecurrenceEnd | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
