// @ts-nocheck
/** tauri-specta globals **/
import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openCalendar() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|open_calendar") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCalendars() : Promise<Result<AppleCalendar[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(filter: EventFilter) : Promise<Result<AppleEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:apple-calendar|list_events", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
calendarChangedEvent: CalendarChangedEvent
}>({
calendarChangedEvent: "plugin:apple-calendar:calendar-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Alarm = { absolute_date: string | null; relative_offset: number | null; proximity: AlarmProximity | null; alarm_type: AlarmType | null; email_address: string | null; sound_name: string | null; url: string | null; structured_location: StructuredLocation | null }
export type AlarmProximity = "None" | "Enter" | "Leave"
export type AlarmType = "Display" | "Audio" | "Procedure" | "Email"
export type AppleCalendar = { id: string; title: string; calendar_type: CalendarType; color: CalendarColor | null; allows_content_modifications: boolean; is_immutable: boolean; is_subscribed: boolean; supported_event_availabilities: EventAvailability[]; allowed_entity_types: CalendarEntityType[]; source: CalendarSource }
export type AppleEvent = { event_identifier: string; calendar_item_identifier: string; external_identifier: string; calendar: CalendarRef; title: string; location: string | null; url: string | null; notes: string | null; creation_date: string | null; last_modified_date: string | null; time_zone: string | null; start_date: string; end_date: string; is_all_day: boolean; availability: EventAvailability; status: EventStatus; has_alarms: boolean; has_attendees: boolean; has_notes: boolean; has_recurrence_rules: boolean; organizer: Participant | null; attendees: Participant[]; structured_location: StructuredLocation | null; recurrence: RecurrenceInfo | null; occurrence_date: string | null; is_detached: boolean; alarms: Alarm[]; birthday_contact_identifier: string | null; is_birthday: boolean }
export type CalendarChangedEvent = null
export type CalendarColor = { red: number; green: number; blue: number; alpha: number }
export type CalendarEntityType = "Event" | "Reminder"
export type CalendarRef = { id: string; title: string }
export type CalendarSource = { identifier: string; title: string; source_type: CalendarSourceType }
export type CalendarSourceType = "Local" | "Exchange" | "CalDav" | "MobileMe" | "Subscribed" | "Birthdays"
export type CalendarType = "Local" | "CalDav" | "Exchange" | "Subscription" | "Birthday"
export type EventAvailability = "NotSupported" | "Busy" | "Free" | "Tentative" | "Unavailable"
export type EventFilter = { from: string; to: string; calendar_tracking_id: string }
export type EventStatus = "None" | "Confirmed" | "Tentative" | "Canceled"
export type GeoLocation = { latitude: number; longitude: number }
export type Participant = { name: string | null; email: string | null; is_current_user: boolean; role: ParticipantRole; status: ParticipantStatus; participant_type: ParticipantType; schedule_status: ParticipantScheduleStatus | null; url: string | null; contact: ParticipantContact | null }
export type ParticipantContact = { identifier: string; given_name: string | null; family_name: string | null; middle_name: string | null; organization_name: string | null; job_title: string | null; email_addresses: string[]; phone_numbers: string[]; url_addresses: string[]; image_available: boolean }
export type ParticipantRole = "Unknown" | "Required" | "Optional" | "Chair" | "NonParticipant"
export type ParticipantScheduleStatus = "None" | "Pending" | "Sent" | "Delivered" | "RecipientNotRecognized" | "NoPrivileges" | "DeliveryFailed" | "CannotDeliver"
export type ParticipantStatus = "Unknown" | "Pending" | "Accepted" | "Declined" | "Tentative" | "Delegated" | "Completed" | "InProgress"
export type ParticipantType = "Unknown" | "Person" | "Room" | "Resource" | "Group"
export type RecurrenceDayOfWeek = { weekday: Weekday; week_number: number | null }
export type RecurrenceEnd = { Count: number } | { Until: string }
export type RecurrenceFrequency = "Daily" | "Weekly" | "Monthly" | "Yearly"
export type RecurrenceInfo = { series_identifier: string; has_recurrence_rules: boolean; occurrence: RecurrenceOccurrence | null; rules: RecurrenceRule[] }
export type RecurrenceOccurrence = { original_start: string; is_detached: boolean }
export type RecurrenceRule = { frequency: RecurrenceFrequency; interval: number; days_of_week: RecurrenceDayOfWeek[]; days_of_month: number[]; months_of_year: number[]; weeks_of_year: number[]; days_of_year: number[]; set_positions: number[]; first_day_of_week: Weekday | null; end: RecurrenceEnd | null }
export type StructuredLocation = { title: string; geo: GeoLocation | null; radius: number | null }
export type Weekday = "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday"

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
