// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async capabilities() : Promise<Result<ActivityCaptureCapabilities, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|capabilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshot() : Promise<Result<ActivityCaptureSnapshot | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async start() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRunning() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|is_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
activityCapturePluginEvent: ActivityCapturePluginEvent
}>({
activityCapturePluginEvent: "plugin:activity-capture:activity-capture-plugin-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivityCaptureCapabilities = { canWatch: boolean; canCaptureVisibleText: boolean; canCaptureBrowserUrl: boolean; requiresAccessibilityPermission: boolean }
export type ActivityCaptureErrorKind = "permission_denied" | "unsupported" | "temporarily_unavailable" | "platform"
export type ActivityCaptureEvent = { startedAtMs: number; endedAtMs: number; fingerprint: string; snapshot: ActivityCaptureSnapshot }
export type ActivityCapturePluginEvent = { type: "activityCaptureTransition"; transition: ActivityCaptureTransition } | { type: "activityCaptureError"; kind: ActivityCaptureErrorKind; message: string }
export type ActivityCaptureSnapshot = { capturedAtMs: number; pid: number; appName: string; bundleId: string | null; windowTitle: string; url: string | null; visibleText: string; source: ActivityCaptureSource }
export type ActivityCaptureSource = "accessibility" | "workspace"
export type ActivityCaptureTransition = { previous: ActivityCaptureEvent | null; current: ActivityCaptureEvent | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
