// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async capabilities() : Promise<Result<ActivityCaptureCapabilities, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|capabilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshot() : Promise<Result<ActivityCaptureSnapshot | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async latestScreenshotAnalysis() : Promise<Result<ActivityCaptureScreenshotAnalysis | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|latest_screenshot_analysis") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAnalysesInRange(startMs: number, endMs: number) : Promise<Result<ActivityCaptureScreenshotAnalysis[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|list_analyses_in_range", { startMs, endMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async status() : Promise<Result<ActivityCaptureStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async start() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRunning() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|is_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configure(input: ConfigureInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|configure", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDailySummarySnapshot(input: LoadDailySummarySnapshotInput) : Promise<Result<DailySummarySnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|get_daily_summary_snapshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDailySummary(input: SaveDailySummaryInput) : Promise<Result<StoredDailySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:activity-capture|save_daily_summary", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
activityCapturePluginEvent: ActivityCapturePluginEvent
}>({
activityCapturePluginEvent: "plugin:activity-capture:activity-capture-plugin-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivityCaptureAppIdentity = { pid: number; appName: string; appId: string; appIdKind: AppIdKind; bundleId: string | null; executablePath: string | null }
export type ActivityCaptureBudget = { minIntervalSecs: number }
export type ActivityCaptureCapabilities = { canWatch: boolean; canCaptureVisibleText: boolean; canCaptureBrowserUrl: boolean; requiresAccessibilityPermission: boolean }
export type ActivityCapturePluginEvent = { type: "activityCaptureStateChanged"; state: ActivityCaptureStateChanged } | { type: "activityCaptureSignal"; signal: ActivityCaptureSignal } | { type: "activityCaptureError"; error: ActivityCaptureRuntimeError } | { type: "activityCaptureScreenshotAnalysis"; analysis: ActivityCaptureScreenshotAnalysis } | { type: "activityCaptureScreenshotAnalysisError"; error: ActivityCaptureScreenshotAnalysisError }
export type ActivityCaptureRuntimeError = { kind: CaptureErrorKind; message: string; occurredAtMs: number }
export type ActivityCaptureScreenshotAnalysis = { fingerprint: string; reason: TransitionReason; capturedAtMs: number; appName: string; windowTitle: string | null; summary: string }
export type ActivityCaptureScreenshotAnalysisError = { fingerprint: string; capturedAtMs: number; appName: string; windowTitle: string | null; message: string }
export type ActivityCaptureSignal = { sequence: number; occurredAtMs: number; reason: TransitionReason; suppressedSnapshotCount: number; fingerprint: string | null; snapshot: ActivityCaptureSnapshot | null }
export type ActivityCaptureSnapshot = { app: ActivityCaptureAppIdentity; activityKind: ActivityKind; capturedAtMs: number; pid: number; appName: string; bundleId: string | null; windowTitle: string | null; url: string | null; visibleText: string | null; textAnchorKind: TextAnchorKind | null; textAnchorIdentity: string | null; textAnchorText: string | null; textAnchorPrefix: string | null; textAnchorSuffix: string | null; textAnchorSelectedText: string | null; textAnchorConfidence: TextAnchorConfidence | null; contentLevel: ContentLevel; source: SnapshotSource }
export type ActivityCaptureStateChanged = { isRunning: boolean; changedAtMs: number }
export type ActivityCaptureStatus = { isRunning: boolean; lastStateChangedAtMs: number | null; lastSignal: ActivityCaptureSignal | null; lastError: ActivityCaptureRuntimeError | null; lastScreenshotAnalysis: ActivityCaptureScreenshotAnalysis | null; lastScreenshotAnalysisError: ActivityCaptureScreenshotAnalysisError | null; budget: ActivityCaptureBudget; analyzeScreenshots: boolean; screenshotsToday: number; screenshotsThisHour: number; storageUsedMb: number }
export type ActivityKind = "foreground_window" | "browser" | "audio_session"
export type AppIdKind = "bundle_id" | "executable_path" | "process_name" | "pid"
export type CaptureErrorKind = "permission_denied" | "unsupported" | "temporarily_unavailable" | "platform"
export type ConfigureInput = { budget: ActivityCaptureBudget | null; analyzeScreenshots: boolean | null }
export type ContentLevel = "metadata" | "url" | "full"
export type DailyActivityAnalysis = { capturedAtMs: number; fingerprint: string; appName: string; windowTitle: string | null; reason: string; summary: string }
export type DailyActivityAppStat = { appName: string; count: number }
export type DailyActivityStats = { signalCount: number; screenshotCount: number; analysisCount: number; uniqueAppCount: number; firstSignalAtMs: number | null; lastSignalAtMs: number | null; topApps: DailyActivityAppStat[] }
export type DailySummarySnapshot = { stats: DailyActivityStats; analyses: DailyActivityAnalysis[]; summary: StoredDailySummary | null; sourceCursorMs: number; sourceFingerprint: string }
export type DailySummaryTimelineItem = { time: string; summary: string }
export type DailySummaryTopic = { title: string; summary: string }
export type LoadDailySummarySnapshotInput = { date: string; startMs: number; endMs: number }
export type SaveDailySummaryInput = { date: string; content: string; timeline: DailySummaryTimelineItem[]; topics: DailySummaryTopic[]; sourceCursorMs: number; sourceFingerprint: string; generatedAt: string }
export type SnapshotSource = "accessibility" | "workspace"
export type StoredDailySummary = { id: string; date: string; content: string; timeline: DailySummaryTimelineItem[]; topics: DailySummaryTopic[]; status: string; sourceCursorMs: number; sourceFingerprint: string; generatedAt: string; generationError: string; updatedAt: string }
export type TextAnchorConfidence = "high" | "medium" | "low"
export type TextAnchorKind = "focused_edit" | "selected_text" | "focused_element" | "document" | "none"
export type TransitionReason = "started" | "idle" | "app_changed" | "activity_kind_changed" | "url_changed" | "title_changed" | "text_anchor_changed" | "content_changed"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
