// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCalendars() : Promise<Result<CalendarListEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:google-calendar|list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(filter: EventFilter) : Promise<Result<Event[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:google-calendar|list_events", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccessRole = "freeBusyReader" | "reader" | "writer" | "owner" | "unknown"
export type Attendee = { id?: string | null; email?: string | null; displayName?: string | null; organizer?: boolean | null; self?: boolean | null; resource?: boolean | null; optional?: boolean | null; responseStatus?: AttendeeResponseStatus | null; comment?: string | null; additionalGuests?: number | null }
export type AttendeeResponseStatus = "needsAction" | "declined" | "tentative" | "accepted" | "unknown"
export type AutoDeclineMode = "declineNone" | "declineAllConflictingInvitations" | "declineOnlyNewConflictingInvitations" | "unknown"
export type BirthdayProperties = { contact?: string | null; type?: BirthdayPropertyType | null; customTypeName?: string | null }
export type BirthdayPropertyType = "birthday" | "anniversary" | "self" | "other" | "custom" | "unknown"
export type CalendarListEntry = { id: string; kind?: string | null; etag?: string | null; summary?: string | null; description?: string | null; location?: string | null; timeZone?: string | null; summaryOverride?: string | null; colorId?: string | null; backgroundColor?: string | null; foregroundColor?: string | null; hidden?: boolean | null; selected?: boolean | null; primary?: boolean | null; deleted?: boolean | null; accessRole?: AccessRole | null; dataOwner?: string | null; defaultReminders?: Reminder[] | null; notificationSettings?: NotificationSettings | null; conferenceProperties?: ConferenceProperties | null; autoAcceptInvitations?: boolean | null }
export type CalendarNotification = { method: NotificationMethod; type: NotificationType }
export type ChatStatus = "available" | "doNotDisturb" | "unknown"
export type ConferenceCreateRequest = { requestId?: string | null; conferenceSolutionKey?: ConferenceSolutionKey | null; status?: ConferenceCreateRequestStatus | null }
export type ConferenceCreateRequestStatus = { statusCode: ConferenceCreateStatusCode }
export type ConferenceCreateStatusCode = "pending" | "success" | "failure" | "unknown"
export type ConferenceData = { conferenceId?: string | null; conferenceSolution?: ConferenceSolution | null; entryPoints?: EntryPoint[] | null; createRequest?: ConferenceCreateRequest | null; notes?: string | null; signature?: string | null }
export type ConferenceProperties = { allowedConferenceSolutionTypes?: ConferenceSolutionType[] | null }
export type ConferenceSolution = { key?: ConferenceSolutionKey | null; name?: string | null; iconUri?: string | null }
export type ConferenceSolutionKey = { type: ConferenceSolutionType }
export type ConferenceSolutionType = "addOn" | "hangoutsMeet" | "eventNamedHangout" | "eventHangout" | "unknown"
export type CustomLocation = { label?: string | null }
export type EntryPoint = { entryPointType: EntryPointType; uri: string; label?: string | null; pin?: string | null; accessCode?: string | null; meetingCode?: string | null; passcode?: string | null; password?: string | null }
export type EntryPointType = "video" | "phone" | "sip" | "more" | "unknown"
export type Event = { id: string; kind?: string | null; etag?: string | null; status?: EventStatus | null; htmlLink?: string | null; created?: string | null; updated?: string | null; summary?: string | null; description?: string | null; location?: string | null; colorId?: string | null; creator?: EventPerson | null; organizer?: EventPerson | null; start?: EventDateTime | null; end?: EventDateTime | null; endTimeUnspecified?: boolean | null; recurrence?: string[] | null; recurringEventId?: string | null; originalStartTime?: EventDateTime | null; transparency?: Transparency | null; visibility?: Visibility | null; iCalUID?: string | null; sequence?: number | null; attendees?: Attendee[] | null; attendeesOmitted?: boolean | null; extendedProperties?: ExtendedProperties | null; hangoutLink?: string | null; conferenceData?: ConferenceData | null; gadget?: Gadget | null; anyoneCanAddSelf?: boolean | null; guestsCanInviteOthers?: boolean | null; guestsCanModify?: boolean | null; guestsCanSeeOtherGuests?: boolean | null; privateCopy?: boolean | null; locked?: boolean | null; reminders?: Reminders | null; source?: EventSource | null; workingLocationProperties?: WorkingLocationProperties | null; outOfOfficeProperties?: OutOfOfficeProperties | null; focusTimeProperties?: FocusTimeProperties | null; attachments?: EventAttachment[] | null; birthdayProperties?: BirthdayProperties | null; eventType?: EventType | null }
export type EventAttachment = { fileUrl?: string | null; title?: string | null; mimeType?: string | null; iconLink?: string | null; fileId?: string | null }
export type EventDateTime = { date?: string | null; dateTime?: string | null; timeZone?: string | null }
export type EventFilter = { from: string; to: string; calendar_tracking_id: string }
export type EventPerson = { id?: string | null; email?: string | null; displayName?: string | null; self?: boolean | null }
export type EventSource = { url: string; title: string }
export type EventStatus = "confirmed" | "tentative" | "cancelled" | "unknown"
export type EventType = "default" | "birthday" | "focusTime" | "fromGmail" | "outOfOffice" | "workingLocation" | "unknown"
export type ExtendedProperties = { private?: Partial<{ [key in string]: string }> | null; shared?: Partial<{ [key in string]: string }> | null }
export type FocusTimeProperties = { autoDeclineMode?: AutoDeclineMode | null; declineMessage?: string | null; chatStatus?: ChatStatus | null }
export type Gadget = { type?: string | null; title?: string | null; link?: string | null; iconLink?: string | null; width?: number | null; height?: number | null; display?: GadgetDisplay | null; preferences?: Partial<{ [key in string]: string }> | null }
export type GadgetDisplay = "chip" | "icon" | "unknown"
export type NotificationMethod = "email" | "unknown"
export type NotificationSettings = { notifications?: CalendarNotification[] | null }
export type NotificationType = "eventCreation" | "eventChange" | "eventCancellation" | "eventResponse" | "agenda" | "unknown"
export type OfficeLocation = { buildingId?: string | null; floorId?: string | null; floorSectionId?: string | null; deskId?: string | null; label?: string | null }
export type OutOfOfficeProperties = { autoDeclineMode?: AutoDeclineMode | null; declineMessage?: string | null }
export type Reminder = { method: ReminderMethod; minutes: number }
export type ReminderMethod = "email" | "popup" | "unknown"
export type Reminders = { useDefault?: boolean | null; overrides?: Reminder[] | null }
export type Transparency = "opaque" | "transparent" | "unknown"
export type Visibility = "default" | "public" | "private" | "confidential" | "unknown"
export type WorkingLocationProperties = { type?: WorkingLocationType | null; customLocation?: CustomLocation | null; officeLocation?: OfficeLocation | null }
export type WorkingLocationType = "homeOffice" | "officeLocation" | "customLocation" | "unknown"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
