// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async runBatch(params: BatchParams) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|run_batch", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseSubtitle(path: string) : Promise<Result<Subtitle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|parse_subtitle", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportToVtt(sessionId: string, words: VttWord[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|export_to_vtt", { sessionId, words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSupportedLanguagesBatch(provider: string, model: string | null, languages: string[]) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|is_supported_languages_batch", { provider, model, languages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suggestProvidersForLanguagesBatch(languages: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|suggest_providers_for_languages_batch", { languages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDocumentedLanguageCodesBatch() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:listener2|list_documented_language_codes_batch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
batchEvent: BatchEvent
}>({
batchEvent: "plugin:listener2:batch-event"
})

/** user-defined constants **/



/** user-defined types **/

export type BatchEvent = { type: "batchStarted"; session_id: string } | { type: "batchProgress"; session_id: string; delta: TranscriptDelta; percentage: number } | { type: "batchEnded"; session_id: string } | { type: "batchFailed"; session_id: string; error: string }
export type BatchParams = { session_id: string; provider: BatchProvider; file_path: string; model?: string | null; base_url: string; api_key: string; languages?: string[]; keywords?: string[] }
export type BatchProvider = "deepgram" | "soniox" | "assemblyai" | "am"
export type FinalizedWord = { id: string; text: string; start_ms: number; end_ms: number; channel: number; state: WordState }
export type PartialWord = { text: string; start_ms: number; end_ms: number; channel: number }
export type SpeakerHint = { word_id: string; speaker_index: number }
export type Subtitle = { tokens: Token[] }
export type Token = { text: string; start_time: number; end_time: number; speaker: string | null }
/**
 * Delta emitted to the frontend after processing.
 * 
 * The frontend should:
 * 1. Remove words listed in `replaced_ids` from TinyBase
 * 2. Persist `new_words` to TinyBase (honoring `state`)
 * 3. Store `partials` in ephemeral Zustand state for rendering
 * 
 * This shape handles all correction flows uniformly:
 * - Normal finalization: `new_words` with `Final`, empty `replaced_ids`
 * - Pending correction submitted: `new_words` with `Pending`, `replaced_ids`
 * pointing at the same words' previous `Final` versions
 * - Correction resolved: `new_words` with `Final` (corrected text),
 * `replaced_ids` pointing at the `Pending` versions
 */
export type TranscriptDelta = { new_words: FinalizedWord[]; hints: SpeakerHint[]; 
/**
 * IDs of words superseded by `new_words`. Empty for normal finalization.
 */
replaced_ids: string[]; 
/**
 * Current in-progress words across all channels. Global snapshot.
 */
partials: PartialWord[] }
export type VttWord = { text: string; start_ms: number; end_ms: number; speaker: string | null }
/**
 * Lifecycle state of a word in the transcript.
 * 
 * - `Partial`: still being streamed, ephemeral (not persisted).
 * - `Pending`: confirmed by the STT model but a correction source (cloud STT
 * fallback, LLM postprocessor, etc.) is still processing it. The word has an
 * ID and is persisted, but its text may be replaced when the correction
 * resolves via `TranscriptDelta::replaced_ids`.
 * - `Final`: stable, will not change.
 */
export type WordState = "partial" | "pending" | "final"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
