pub struct TaskRow {
    pub id: String,
    pub daily_id: String,
    pub parent_task_id: Option<String>,
    pub event_id: Option<String>,
    pub sort_key: String,
    pub task_type: String,
    pub title: String,
    pub status: String,
    pub source_id: String,
    pub source_url: String,
    pub metadata_json: String,
    pub user_id: String,
    pub visibility: String,
    pub created_at: String,
    pub updated_at: String,
    pub updated_by: String,
}

pub struct TaskWithEventRow {
    pub id: String,
    pub daily_id: String,
    pub parent_task_id: Option<String>,
    pub event_id: Option<String>,
    pub sort_key: String,
    pub task_type: String,
    pub title: String,
    pub status: String,
    pub source_id: String,
    pub source_url: String,
    pub metadata_json: String,
    pub user_id: String,
    pub visibility: String,
    pub created_at: String,
    pub updated_at: String,
    pub updated_by: String,
    pub event_tracking_id: Option<String>,
    pub event_started_at: Option<String>,
    pub event_ended_at: Option<String>,
    pub event_is_all_day: Option<bool>,
    pub event_meeting_link: Option<String>,
    pub event_location: Option<String>,
    pub event_sync_status: Option<String>,
    pub event_deleted_at: Option<String>,
}
