#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActivitySignalRow {
    pub id: String,
    pub occurred_at_ms: i64,
    pub transition_sequence: i64,
    pub reason: String,
    pub app_id: String,
    pub bundle_id: String,
    pub app_name: String,
    pub activity_kind: String,
    pub window_title: String,
    pub url: String,
    pub domain: String,
    pub content_level: String,
    pub source: String,
    pub text_anchor_identity: String,
    pub fingerprint: String,
    pub payload_json: String,
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActivitySegmentRow {
    pub id: String,
    pub started_at_ms: i64,
    pub ended_at_ms: i64,
    pub duration_ms: i64,
    pub date: String,
    pub semantic_key: String,
    pub app_id: String,
    pub bundle_id: String,
    pub app_name: String,
    pub activity_kind: String,
    pub title: String,
    pub url: String,
    pub domain: String,
    pub payload_json: String,
    pub source_signal_start_id: Option<String>,
    pub source_signal_end_id: Option<String>,
    pub linked_task_id: Option<String>,
    pub linked_daily_note_id: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}
