// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|list_input_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|list_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultInputDevice() : Promise<Result<AudioDevice | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_default_input_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultOutputDevice() : Promise<Result<AudioDevice | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_default_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultInputDevice(deviceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|set_default_input_device", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultOutputDevice(deviceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|set_default_output_device", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isHeadphone(device: AudioDevice) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|is_headphone", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadState() : Promise<Result<PriorityState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|load_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveState(state: PriorityState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|save_state", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInputPriorities() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_input_priorities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpeakerPriorities() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_speaker_priorities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHeadphonePriorities() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_headphone_priorities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveInputPriorities(priorities: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|save_input_priorities", { priorities }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSpeakerPriorities(priorities: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|save_speaker_priorities", { priorities }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveHeadphonePriorities(priorities: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|save_headphone_priorities", { priorities }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveDeviceToTop(deviceId: string, direction: AudioDirection, category: OutputCategory | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|move_device_to_top", { deviceId, direction, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDeviceCategory(deviceId: string) : Promise<Result<OutputCategory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_device_category", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceCategory(deviceId: string, category: OutputCategory) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|set_device_category", { deviceId, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentMode() : Promise<Result<OutputCategory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_current_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentMode(mode: OutputCategory) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|set_current_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isCustomMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|is_custom_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCustomMode(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|set_custom_mode", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getKnownDevices() : Promise<Result<StoredDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|get_known_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rememberDevice(uid: string, name: string, isInput: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|remember_device", { uid, name, isInput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forgetDevice(uid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|forget_device", { uid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isDeviceHidden(deviceId: string, direction: AudioDirection) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|is_device_hidden", { deviceId, direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideDevice(deviceId: string, direction: AudioDirection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|hide_device", { deviceId, direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unhideDevice(deviceId: string, direction: AudioDirection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:audio-priority|unhide_device", { deviceId, direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Represents an audio device with stable identification.
 */
export type AudioDevice = { 
/**
 * Stable, platform-specific device identifier
 */
id: DeviceId; 
/**
 * Human-readable device name
 */
name: string; 
/**
 * Device direction (input/output)
 */
direction: AudioDirection; 
/**
 * Transport type (USB, Bluetooth, etc.)
 */
transport_type: TransportType; 
/**
 * Whether this device is currently the system default
 */
is_default: boolean; 
/**
 * Volume level (0.0 to 1.0), if available
 */
volume?: number | null; 
/**
 * Whether the device is muted, if available
 */
is_muted?: boolean | null }
/**
 * Audio device direction (input or output).
 */
export type AudioDirection = 
/**
 * Input device (microphone)
 */
"Input" | 
/**
 * Output device (speaker/headphone)
 */
"Output"
/**
 * A stable, platform-specific device identifier.
 * 
 * On macOS: CoreAudio device UID (e.g., "BuiltInMicrophoneDevice")
 * On Linux: PulseAudio source/sink name (e.g., "alsa_input.pci-0000_00_1f.3.analog-stereo")
 * On Windows: IMMDevice endpoint ID
 */
export type DeviceId = string
/**
 * Output device category for priority management.
 */
export type OutputCategory = 
/**
 * Speaker devices (external speakers, built-in speakers)
 */
"Speaker" | 
/**
 * Headphone/headset devices
 */
"Headphone"
/**
 * Persistent state for priority management.
 */
export type PriorityState = { input_priorities: string[]; speaker_priorities: string[]; headphone_priorities: string[]; device_categories: Partial<{ [key in string]: OutputCategory }>; hidden_mics: string[]; hidden_speakers: string[]; hidden_headphones: string[]; known_devices: StoredDevice[]; current_mode: OutputCategory; is_custom_mode: boolean }
/**
 * A stored device with metadata for persistence.
 */
export type StoredDevice = { uid: string; name: string; is_input: boolean; last_seen: number }
/**
 * Transport type for audio devices.
 * 
 * Used to determine device category (headphone vs speaker) and priority.
 */
export type TransportType = 
/**
 * Built-in device (internal speakers, internal mic)
 */
"BuiltIn" | 
/**
 * USB audio device
 */
"Usb" | 
/**
 * Bluetooth audio device
 */
"Bluetooth" | 
/**
 * HDMI/DisplayPort audio
 */
"Hdmi" | 
/**
 * PCI audio device
 */
"Pci" | 
/**
 * Virtual/aggregate device
 */
"Virtual" | 
/**
 * Unknown transport type
 */
"Unknown"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
