-- Make audio-files bucket private for security
-- Files will be accessed via signed URLs generated by the backend service

UPDATE storage.buckets
SET public = false
WHERE id = 'audio-files';

-- Drop the public SELECT policy since the bucket is now private
DROP POLICY IF EXISTS "audio_files_select_all" ON storage.objects;

-- Add a policy for authenticated users to SELECT their own files
CREATE POLICY "audio_files_select_owner" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'audio-files' AND auth.uid()::text = (storage.foldername(name))[1]);
