# Set base directory to "apps/unsigned-web" in Netlify UI
[build]
command = "pnpm -F @hypr/unsigned-web build"
publish = "apps/unsigned-web/dist"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "/"
status = 200
